=== x7finance/monorepo/packages/token-lists/src/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://www.x7finance.org/tokenlist.schema.json",
  "title": "Xchange Token List",
  "description": "Schema for lists of tokens compatible with the Xchange Interface",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Ethereum network where this token is deployed",
          "minimum": 1
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$"
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token",
          "minLength": 1,
          "maxLength": 20
        },
        "extensions": {
          "type": "object",
          "description": "Optional metadata for the token",
          "additionalProperties": true
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 50
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "$ref": "#/definitions/TokenInfo"
      },
      "minItems": 1
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "additionalProperties": true
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri-reference"
    }
  },
  "required": ["name", "timestamp", "version", "tokens"]
}

=== x7finance/monorepo/apps/org/public/lists/coingecko/opti.json
{
  "name": "CoinGecko",
  "logoURI": "https://static.coingecko.com/s/thumbnail-007177f3eca19695592f0b8b0eabbdae282b54154e1be912285c9034ea6cbaf2.png",
  "keywords": ["defi"],
  "timestamp": "2024-09-18T17:00:29.296+00:00",
  "tokens": [
    {
      "chainId": 10,
      "address": "0x0d82b5d3a8420c285c6d353a6bdc30d164bb50f0",
      "name": "Aktionariat Sportsparadise Switzerland ",
      "symbol": "SPOS",
      "decimals": 0,
      "logoURI": "https://assets.coingecko.com/coins/images/33391/thumb/SPOS.png?1701680250"
    },
    {
      "chainId": 10,
      "address": "0x8fb94e08bc984497aaaf1a545ed455be89f8c675",
      "name": "Aktionariat TV PLUS AG Tokenized Shares",
      "symbol": "TVPLS",
      "decimals": 0,
      "logoURI": "https://assets.coingecko.com/coins/images/33375/thumb/TVPLS.png?1701649948"
    },
    {
      "chainId": 10,
      "address": "0x69420f9e38a4e60a62224c489be4bf7a94402496",
      "name": "Defi money",
      "symbol": "MONEY",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/39230/thumb/Token_2x-1.png?1725438128"
    },
    {
      "chainId": 10,
      "address": "0x4186bfc76e2e237523cbc30fd220fe055156b41f",
      "name": "KelpDAO Bridged rsETH  Optimism ",
      "symbol": "RSETH",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/39548/thumb/rseth.png?1722850416"
    },
    {
      "chainId": 10,
      "address": "0x5ad323d764301e057614edb0449f470d68ea9485",
      "name": "Aktionariat SIA Swiss Influencer Award ",
      "symbol": "SIAS",
      "decimals": 0,
      "logoURI": "https://assets.coingecko.com/coins/images/33373/thumb/SIA.png?1701649606"
    },
    {
      "chainId": 10,
      "address": "0x6926b434cce9b5b7966ae1bfeef6d0a7dcf3a8bb",
      "name": "Exactly USD Coin",
      "symbol": "EXAUSDC",
      "decimals": 6,
      "logoURI": "https://assets.coingecko.com/coins/images/50240/thumb/exaUSDC.png?1726676118"
    },
    {
      "chainId": 10,
      "address": "0x68f180fcce6836688e9084f035309e29bf0a2095",
      "name": "Optimism Bridged WBTC  Optimism ",
      "symbol": "WBTC",
      "decimals": 8,
      "logoURI": "https://assets.coingecko.com/coins/images/39553/thumb/wbtc.png?1722897341"
    },
    {
      "chainId": 10,
      "address": "0x22ab31cd55130435b5efbf9224b6a9d5ec36533f",
      "name": "Exactly Wrapped stETH",
      "symbol": "EXAWSTETH",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/31172/thumb/ExawstETH_1.png?1696530000"
    },
    {
      "chainId": 10,
      "address": "0xb5090d514bcaca7dafb7e52763658844121f346d",
      "name": "Binary Holdings",
      "symbol": "BNRY",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/37521/thumb/Vector-1.png?1714634222"
    },
    {
      "chainId": 10,
      "address": "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1",
      "name": "MakerDAO Optimism Bridged DAI  Optimism",
      "symbol": "DAI",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/39818/thumb/dai.png?1724190656"
    },
    {
      "chainId": 10,
      "address": "0x6f748fd65d7c71949ba6641b3248c4c191f3b322",
      "name": "Exactly WBTC",
      "symbol": "EXAWBTC",
      "decimals": 8
    },
    {
      "chainId": 10,
      "address": "0x96d17e1301b31556e5e263389583a9331e6749e9",
      "name": "RillaFi",
      "symbol": "RILLA",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/29193/thumb/output-onlinepngtools.png?1696528152"
    },
    {
      "chainId": 10,
      "address": "0xc3248a1bd9d72fa3da6e6ba701e58cbf818354eb",
      "name": "HANePlatform",
      "symbol": "HANEP",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/35202/thumb/HANeP_200px.png?1707842735"
    },
    {
      "chainId": 10,
      "address": "0xa430a427bd00210506589906a71b54d6c256cedb",
      "name": "Exactly Optimism",
      "symbol": "EXAOP",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/31173/thumb/ExaOP_1.png?1696530001"
    },
    {
      "chainId": 10,
      "address": "0xc26921b5b9ee80773774d36c84328ccb22c3a819",
      "name": "Wrapped OptiDoge",
      "symbol": "WOPTIDOGE",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/31066/thumb/Wrapped_OptiDoge_logo_200x200px_.png?1696529900"
    },
    {
      "chainId": 10,
      "address": "0xf467c7d5a4a9c4687ffc7986ac6ad5a4c81e1404",
      "name": "Kite",
      "symbol": "KITE",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/35343/thumb/_KITE.png?1708317581"
    },
    {
      "chainId": 10,
      "address": "0xb9243c495117343981ec9f8aa2abffee54396fc0",
      "name": "Perpetual Delta Neutral Yield  Optimism",
      "symbol": "USDPY",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/40153/thumb/usdpy.png?1726073418"
    },
    {
      "chainId": 10,
      "address": "0xdc8840a0a1ebf8be5ace62a7d9360dfcb26adffc",
      "name": "HappyAI",
      "symbol": "SMILEAI",
      "decimals": 13,
      "logoURI": "https://assets.coingecko.com/coins/images/34824/thumb/smileai.jpg?1706189986"
    },
    {
      "chainId": 10,
      "address": "0x29cb69d4780b53c1e5cd4d2b817142d2e9890715",
      "name": "PoolTogether Prize WETH   Aave",
      "symbol": "PWETH",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/32454/thumb/PrizeWETHIcon_200.png?1698241047"
    },
    {
      "chainId": 10,
      "address": "0x17aabf6838a6303fc6e9c5a227dc1eb6d95c829a",
      "name": "Magicaltux",
      "symbol": "TUX",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/33909/thumb/1703316796-picsay.png?1703453966"
    },
    {
      "chainId": 10,
      "address": "0xc3864f98f2a61a7caeb95b039d031b4e2f55e0e9",
      "name": "OpenXSwap",
      "symbol": "OPENX",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/27663/thumb/openx_BASE.png?1710472693"
    },
    {
      "chainId": 10,
      "address": "0x3ee6107d9c93955acbb3f39871d32b02f82b78ab",
      "name": "Staked Ethos Reserve Note",
      "symbol": "STERN",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/31522/thumb/stERN.png?1696530332"
    },
    {
      "chainId": 10,
      "address": "0xed9b52e6d2df4ad9fc258254e1e5ef5ad0b3ca3c",
      "name": "Aktionariat Fieldoo AG Tokenized Shares",
      "symbol": "FDOS",
      "decimals": 0,
      "logoURI": "https://assets.coingecko.com/coins/images/33392/thumb/FDOS.png?1701680368"
    },
    {
      "chainId": 10,
      "address": "0xe64b4eb5eec6343887c4683da31f0ca62ea39ce3",
      "name": "Aktionariat BEE Digital Growth AG Token",
      "symbol": "BEES",
      "decimals": 0,
      "logoURI": "https://assets.coingecko.com/coins/images/33367/thumb/BEES.png?1701613820"
    },
    {
      "chainId": 10,
      "address": "0xfa436399d0458dbe8ab890c3441256e3e09022a8",
      "name": "ZipSwap",
      "symbol": "ZIP",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/22910/thumb/zip.png?1696522207"
    },
    {
      "chainId": 10,
      "address": "0x513c7e3a9c69ca3e22550ef58ac1c0088e918fff",
      "name": "Aave v3 OP",
      "symbol": "AOP",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/32919/thumb/op.png?1699825542"
    },
    {
      "chainId": 10,
      "address": "0xb153fb3d196a8eb25522705560ac152eeec57901",
      "name": "Magic Internet Money  Optimism ",
      "symbol": "MIM",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/37659/thumb/mim.png?1715165153"
    },
    {
      "chainId": 10,
      "address": "0x2513486f18eee1498d7b6281f668b955181dd0d9",
      "name": "OpenXSwap Gov  Token",
      "symbol": "XOPENX",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/28325/thumb/X_op_red_sm.png?1696527332"
    },
    {
      "chainId": 10,
      "address": "0x1cef2d62af4cd26673c7416957cc4ec619a696a7",
      "name": "DexToro",
      "symbol": "DTORO",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/33529/thumb/DTORO_Logo_New.png?1716971115"
    },
    {
      "chainId": 10,
      "address": "0xfe5b10f053871e66a319a57a16cf4e709f51367f",
      "name": "OVERPOWERED",
      "symbol": "OVERPOW",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/38180/thumb/overpowered.png?1716788158"
    },
    {
      "chainId": 10,
      "address": "0x8fc7c1109c08904160d6ae36482b79814d45eb78",
      "name": "Token Engineering Commons",
      "symbol": "TEC",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/18233/thumb/72481541.png?1696517730"
    },
    {
      "chainId": 10,
      "address": "0x48a9f8b4b65a55cc46ea557a610acf227454ab09",
      "name": "OP Chads",
      "symbol": "OPC",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/36580/thumb/smol.png?1711944400"
    },
    {
      "chainId": 10,
      "address": "0x3ed9acaac7bd974eb83a8ea6432a239e3c829d5d",
      "name": "LERNITAS",
      "symbol": "2192",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/36240/thumb/lernitas.jpg?1710920218"
    },
    {
      "chainId": 10,
      "address": "0x61baadcf22d2565b0f471b291c475db5555e0b76",
      "name": "Aelin",
      "symbol": "AELIN",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/22303/thumb/aelien.jpg?1696521649"
    },
    {
      "chainId": 10,
      "address": "0x4200000000000000000000000000000000000042",
      "name": "Optimism",
      "symbol": "OP",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/25244/thumb/Optimism.png?1696524385"
    },
    {
      "chainId": 10,
      "address": "0x73cb180bf0521828d8849bc8cf2b920918e23032",
